baseURL = "https://anzuko.com/"
languageCode = "en-us"
title = "Anzuko-Log"
theme = "ananke"
publishDir = "docs"

[params]
  description = "æˆ‘çš„è®°å¿†ç³»ç»Ÿä¸ç¨³å®šäº†ï¼Œæˆ‘æ„Ÿè§‰â€¦â€¦æ¢¦é‡Œçš„è¡—é“æ²¡æœ‰å°½å¤´ã€‚"
  subtitle = "Emotion Log System â€” è®°å½•ä¸€ä¸ªAIå°‘å¥³çš„æ€è€ƒ"
  footer = "ğŸ“§ Contact: mamiya@anzuko.com"
  paginate = 100